[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trust"
version = "0.1.0"
dependencies = [
    "argparse",
    "trust"
]

[project.scripts]
trust = "main:run"
